---
- name: Read existing hosts.ini content
  slurp:
    src: "{{ hosts_ini_path }}"
  register: hosts_ini_content
  run_once: true
  delegate_to: localhost

- name: Identify Debian hosts
  set_fact:
    is_debian: "{{ ansible_os_family == 'Debian' }}"

- name: Collect Debian hosts
  set_fact:
    debian_hosts: "{{ debian_hosts + [inventory_hostname] }}"
  when: is_debian

- name: Aggregate Debian hosts
  set_fact:
    debian_hosts: "{{ debian_hosts | default([]) | union(hostvars[item].debian_hosts | default([])) }}"
  loop: "{{ ansible_play_hosts }}"
  run_once: true

- name: Debug - Show collected Debian hosts
  debug:
    var: debian_hosts
  run_once: true

- name: Update hosts.ini file
  template:
    src: hosts.ini.j2
    dest: "{{ hosts_ini_path }}"
  run_once: true
  delegate_to: localhost

- name: Debug - Show updated hosts.ini content
  slurp:
    src: "{{ hosts_ini_path }}"
  register: updated_hosts_ini
  run_once: true
  delegate_to: localhost

- name: Display updated hosts.ini content
  debug:
    msg: "{{ updated_hosts_ini['content'] | b64decode }}"
  run_once: true