---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Add deadsnakes repository
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Python version
  ansible.builtin.apt:
    name: python{{ python_version }}
    state: present