---
- name: Gather hardware information
  ansible.builtin.setup:
    gather_subset:
      - 'hardware'
      - 'network'
      - 'virtual'

- name: Update packages cache
  ansible.builtin.apt:
    update_cache: true

- name: Get a list of packages needing updates
  ansible.builtin.shell: apt list --upgradable
  register: apt_packages

- name: Create fact for packages needing updates
  ansible.builtin.set_fact:
    packages_needing_updates: "{{ apt_packages }}"
    when: apt_packages | length > 0
    cacheable: yes

- name: Save hardware information to a report
  ansible.builtin.template:
    src: report.j2
    dest: /tmp/hardware_report.txt

- name: Fetch the hardware report to the local machine
  ansible.builtin.fetch:
    src: /tmp/hardware_report.txt
    dest: "{{ playbook_dir }}/../artifacts/{{ inventory_hostname }}_hardware_report.txt"
    flat: true
