---
- name: Create a new user
  ansible.builtin.user:
    name: "{{ repo_user }}"
    state: present
    shell: /bin/bash
    password: "{{ repo_user_password | password_hash('sha512') }}"
    update_password: always
    groups: "{{ repo_user_groups }}"
    append: true
    create_home: true
    system: false

- name: Ensure ssh-keygen and required packages are installed
  ansible.builtin.apt:
    name: openssh-client
    state: present
  become: true

- name: Create ssh directory for user
  ansible.builtin.file:
    name: "/home/{{ repo_user }}/.ssh"
    state: directory
    owner: "{{ repo_user }}"
    group: "{{ repo_user }}"
    mode: '0700'

- name: Create ssh key pair
  community.crypto.openssh_keypair:
    path: "/home/{{ repo_user }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    owner: "{{ repo_user }}"
    group: "{{ repo_user }}"
    mode: '0600'
  register: public_key

- name: Create SSH cofnig file
  ansible.builtin.template:
    src: config.j2
    dest: "/home/{{ repo_user }}/.ssh/config"
    owner: "{{ repo_user }}"
    group: "{{ repo_user }}"
    mode: '0600'

- name: Display public key
  ansible.builtin.debug:
    msg: "{{ public_key }}"
