---
- name: Gather hardware information
  ansible.builtin.setup:
    gather_subset:
      - 'hardware'
      - 'network'
      - 'virtual'

- name: Gather facts on listening ports
  community.general.listen_ports_facts:

- name: List TCP ports
  ansible.builtin.debug:
    msg: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"

- name: List UDP ports
  ansible.builtin.debug:
    msg: "{{ ansible_facts.udp_listen | map(attribute='port') | sort | list }}"

- name: Save hardware information to a report
  template:
    src: report.j2
    dest: /tmp/hardware_report.txt

- name: Fetch the hardware report to the local machine
  fetch:
    src: /tmp/hardware_report.txt
    dest: "{{ playbook_dir }}/../artifacts/{{ inventory_hostname }}_hardware_report.txt"
    flat: yes
