---
- name: Install BIND9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Create named.conf file
  template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: '0640'
  notify: Restart BIND9

- name: Create named.conf.options file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0640'
  notify: Restart BIND9

- name: Create forward zone file
  template:
    src: forward.zone.j2
    dest: "/var/lib/bind/{{ dns_domain }}.zone"
    owner: root
    group: bind
    mode: '0640'
  notify: Restart BIND9

- name: Create reverse zone file
  template:
    src: reverse.zone.j2
    dest: "/var/lib/bind/{{ dns_reverse_zone }}.zone"
    owner: root
    group: bind
    mode: '0640'
  notify: Restart BIND9

- name: Ensure BIND9 service is enabled and started
  systemd:
    name: bind9
    enabled: yes
    state: started

- name: Verify BIND9 configuration
  command: named-checkconf
  changed_when: false

- name: Test DNS resolution
  command: "dig @localhost {{ dns_domain }}"
  changed_when: false
  register: dig_result

- name: Display dig result
  debug:
    var: dig_result.stdout_lines

- name: Add handler to restart BIND9
  meta: flush_handlers