---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Add the GitLab Runner repository
  ansible.builtin.command:
    cmd: curl -o /tmp/script.deb.sh https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh 

- name: Install the GitLab Runner repository
  ansible.builtin.command:
    cmd: bash /tmp/script.deb.sh

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install GitLab Runner
  ansible.builtin.apt:
    name: gitlab-runner
    state: present

