---
- name: Create a new user
  ansible.builtin.user:
    name: "{{ repo_user }}"
    state: present
    shell: /bin/bash
    password: "{{ repo_user_password | password_hash('sha512') }}"
    update_password: always
    groups: "{{ repo_user_groups }}"
    append: true
    create_home: true
    system: false
