---
- name: Install aptitude and needrestart
  ansible.builtin.apt:
    name:
      - aptitude
      - needrestart
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade debian system (safe-upgrade)
  ansible.builtin.apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600
  async: '{{ 20 * 60 }}'  # allow up to 20 minutes before timeout

- name: Check if services need to be restarted
  # https://www.captainark.net/2016/01/31/debian-updates-with-ansible/
  ansible.builtin.shell: needrestart -blrl | awk '/^NEEDRESTART-SVC/{print $2}'
  register: needrestart
  changed_when: false

- name: Show services that need to be restarted
  ansible.builtin.debug:
    msg: 'Need to restart these services: {{ needrestart.stdout_lines | join("\n") }}'
  when: needrestart.stdout_lines|length > 0
  changed_when: true

- name: Set the fact of the list of services that need to be restarted
  ansible.builtin.set_fact:
    services_to_restart: "{{ needrestart.stdout_lines | join('\n') }}"
  when: needrestart.stdout_lines | length > 0

- name: Create empty fact if no services need to be restarted
  ansible.builtin.set_fact:
    services_to_restart: "none"
  when: needrestart.stdout_lines | length == 0

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  changed_when: reboot_required_file.stat.exists

- name: Save reboot requirement status as ansible fact
  ansible.builtin.set_fact:
    upgrade_requires_reboot: '{{ reboot_required_file.stat.exists }}'

- name: Save hardware information to a report
  ansible.builtin.template:
    src: report.j2
    dest: /tmp/restart_report.txt

- name: Fetch the hardware report to the local machine
  ansible.builtin.fetch:
    src: /tmp/restart_report.txt
    dest: "{{ playbook_dir }}/../artifacts/{{ inventory_hostname }}_restart_report.txt"
    flat: yes
