---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Download setup script
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_{{ nodejs_version }}.x  
    dest: /tmp/nodesource_setup.sh
    mode: '0755'
  become: true

- name: Run script to enable install of node.js
  ansible.builtin.shell:
    cmd: sudo -E bash /tmp/nodesource_setup.sh
  become: true

- name: Install Node.js
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Verify Node.js installation
  ansible.builtin.command:
    cmd: node -v
  register: node_version

- name: Display Node.js version
  ansible.builtin.debug:
    var: node_version.stdout

- name: Verify npm installation
  ansible.builtin.command:
    cmd: npm -v
  register: npm_version

- name: Display npm version
  ansible.builtin.debug:
    var: npm_version.stdout
