---
- name: Verify NVIDIA Cuda compiler driver version
  command: nvcc --version
  register: nvcc_version
  ignore_errors: yes

- name: Format the output of the nvcc command
  set_fact:
    nvcc_version_output: "{{ nvcc_version.stdout_lines | join('\n') }}"

- name: Verify NVIDIA-SMI
  command: nvidia-smi
  register: nvidia_smi

- name: Format the output of the nvidia-smi command
  set_fact:
    nvidia_smi_output: "{{ nvidia_smi.stdout_lines | join('\n') }}"

- name: Save hardware information to a report
  template:
    src: report.j2
    dest: "{{ playbook_dir }}/../artifacts/{{ inventory_hostname }}_CUDA_report.txt"
  delegate_to: localhost