---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Configure unattended-upgrades for security updates only
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Configure automatic upgrades schedule
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Set system timezone to UTC
  community.general.timezone:
    name: "{{ system_timezone }}"

- name: Ensure unattended-upgrades service is enabled and started
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started
    daemon_reload: true