name: Ansible Test and Lint

on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]

jobs:
  ansible-test-lint:
    name: Ansible Test and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible_admin/playbooks
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint

      - name: Run Ansible Playbook Syntax Check
        run: |
          find . -name "*.yml" -type f -print0 | xargs -0 -I {} ansible-playbook --syntax-check {}